### ISSUE TITLE
Create new release 1.6.1

### ISSUE THREAD

**Issue by wesleybl** [collective/collective.js.galleria#10]
I'm in need of a new release.

@toutpt @vangheem can you please make a new release or add me to pypi so I can do it?

My user on pypi is `wesleybl`

Thanks!

**Comment by toutpt** [comment]
done

**Comment by wesleybl** [comment]
I did release 1.6.1:

https://pypi.org/project/collective.js.galleria/1.6.1

Thanks @toutpt !
